Set('i', Source::Value(31)),
Set('a', Source::Value(1)),
Multiply('p', Source::Value(17)),
Jump(Source::Register('p'), Source::Register('p')),
Multiply('a', Source::Value(2)),
Add('i', Source::Value(-1)),
Jump(Source::Register('i'), Source::Value(-2)),
Add('a', Source::Value(-1)),
Set('i', Source::Value(127)),
Set('p', Source::Value(464)),
Multiply('p', Source::Value(8505)),
Modulo('p', Source::Register('a')),
Multiply('p', Source::Value(129749)),
Add('p', Source::Value(12345)),
Modulo('p', Source::Register('a')),
Set('b', Source::Register('p')),
Modulo('b', Source::Value(10000)),
Sound(Source::Register('b')),
Add('i', Source::Value(-1)),
Jump(Source::Register('i'), Source::Value(-9)),
Jump(Source::Register('a'), Source::Value(3)),
Recover(Source::Register('b')),
Jump(Source::Register('b'), Source::Value(-1)),
Set('f', Source::Value(0)),
Set('i', Source::Value(126)),
Recover(Source::Register('a')),
Recover(Source::Register('b')),
Set('p', Source::Register('a')),
Multiply('p', Source::Value(-1)),
Add('p', Source::Register('b')),
Jump(Source::Register('p'), Source::Value(4)),
Sound(Source::Register('a')),
Set('a', Source::Register('b')),
Jump(Source::Value(1), Source::Value(3)),
Sound(Source::Register('b')),
Set('f', Source::Value(1)),
Add('i', Source::Value(-1)),
Jump(Source::Register('i'), Source::Value(-11)),
Sound(Source::Register('a')),
Jump(Source::Register('f'), Source::Value(-16)),
Jump(Source::Register('a'), Source::Value(-19)),
